=== FIT-Mobility/dimo-tool-suite/shared-js/omp-tool-project-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "OMP Interface Tool Project Schema",
    "type": "object",
    "properties": {
        "project": {
            "$ref": "#/definitions/project"
        },
        "services": {
            "type": "array",
            "description": "This list contains exactly the services defined in the tool including their rich-text documentation.",
            "items": {
                "$ref": "#/definitions/service"
            }
        },
        "sequences": {
            "type": "array",
            "description": "This list contains exactly the sequences defined in the tool including their rich-text documentation.",
            "items": {
                "$ref": "#/definitions/sequence"
            }
        },
        "functions": {
            "type": "array",
            "description": "This list contains exactly the functions defined in the tool including their rich-text documentation.",
            "items": {
                "$ref": "#/definitions/function"
            }
        },
        "datatypes": {
            "type": "array",
            "description": "This list contains exactly the data types specified in the XSD (thus belonging to the namespace given there as target namespace) including their rich-text documentation.",
            "items": {
                "$ref": "#/definitions/datatype"
            }
        },
        "elements": {
            "type": "array",
            "description": "This list contains exactly the top level elements specified in the XSD (thus belonging to the namespace given there as target namespace) including their rich-text documentation.",
            "items": {
                "$ref": "#/definitions/element"
            }
        },
        "schema": {
            "$ref": "#/definitions/schema"
        }
    },
    "definitions": {
        "doc": {
            "type": "object",
            "properties": {
                "english": {
                    "description": "",
                    "type": "string"
                },
                "german": {
                    "description": "",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "english",
                "german"
            ]
        },
        "function": {
            "type": "object",
            "properties": {
                "ncname": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                },
                "inputElementName": {
                    "description": "",
                    "$ref": "#/definitions/qname"
                },
                "outputElementName": {
                    "description": "",
                    "$ref": "#/definitions/qname"
                },
                "assertions": {
                    "type": "array",
                    "description": "",
                    "items": {
                        "$ref": "#/definitions/assertion"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "ncname",
                "documentation",
                "assertions"
            ]
        },
        "assertion": {
            "type": "object",
            "properties": {
                "test": {
                    "description": "",
                    "type": "string"
                },
                "xpathDefaultNamespace": {
                    "description": "",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "test"
            ]
        },
        "project": {
            "type": "object",
            "properties": {
                "title": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                }
            },
            "additionalProperties": false,
            "required": [
                "title",
                "documentation"
            ]
        },
        "sequence": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                }
            },
            "additionalProperties": false,
            "required": [
                "name"
            ]
        },
        "service": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                },
                "functions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sequences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "documentation",
                "functions",
                "sequences"
            ]
        },
        "qname": {
            "type": "object",
            "javaType": "de.fraunhofer.fit.omp.model.json.QName",
            "properties": {
                "namespaceuri": {
                    "description": "URI of the namespace.",
                    "type": "string",
                    "format": "uri"
                },
                "ncname": {
                    "description": "Non-colonized name = local part of the name.",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "namespaceuri",
                "ncname"
            ]
        },
        "datatype": {
            "type": "object",
            "properties": {
                "ncname": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                }
            },
            "additionalProperties": false,
            "required": [
                "ncname",
                "documentation"
            ]
        },
        "element": {
            "type": "object",
            "properties": {
                "ncname": {
                    "description": "",
                    "type": "string"
                },
                "documentation": {
                    "$ref": "#/definitions/doc"
                }
            },
            "additionalProperties": false,
            "required": [
                "ncname",
                "documentation"
            ]
        },
        "schema": {
            "type": "object",
            "properties": {
                "xsd": {
                    "description": "This field contains a string representation of the XML Schema Definition created by the user.",
                    "type": "string"
                },
                "baseURI": {
                    "description": "This field represents a base URI that will be used to resolve relative paths within the xsd.",
                    "type": "string",
                    "format": "uri"
                }
            },
            "additionalProperties": false,
            "required": [
                "xsd"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "project",
        "services",
        "sequences",
        "functions",
        "datatypes",
        "elements",
        "schema"
    ]
}

=== FIT-Mobility/dimo-tool-suite/server-demo/src/main/resources/plugfest-test.json
{
    "project": {
        "title": "PlugFest",
        "documentation": {
            "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p>Dieses Projekt dient prim채r der Demonstration der Werkzeugunterst체tzung im Rahmen des AP 4.1. Es enth채lt lediglich einen Dienst namens Shuttle-Service. Dieser bietet Funktionen f체r die Nutzung eines On-Demand-Ride-Sharing-Dienstes an.</p></body></html>",
            "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
        }
    },
    "elements": [
        {
            "ncname": "GetOffersRequest",
            "documentation": {
                "english": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>",
                "german": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>"
            }
        },
        {
            "ncname": "GetOffersResponse",
            "documentation": {
                "english": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>",
                "german": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>"
            }
        },
        {
            "ncname": "BookingRequest",
            "documentation": {
                "english": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>",
                "german": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>"
            }
        },
        {
            "ncname": "BookingResponse",
            "documentation": {
                "english": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>",
                "german": "<p xmlns=\"http://www.w3.org/1999/xhtml\"><br /></p>"
            }
        }
    ],
    "datatypes": [
        {
            "ncname": "GeneralErrorType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GetOffersRequestType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "FlexibleGeoLocationType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GeoLocationType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GetOffersResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GetOffersSuccessResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "OfferType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "ActualGeoLocationType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "ActualTimeType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GetOffersErrorResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "BookingRequestType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "BookingResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "BookingSuccessResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "BookingErrorResponseType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "LatitudeType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "LongitudeType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "GetOffersErrorCodeType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        },
        {
            "ncname": "BookingErrorCodeType",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            }
        }
    ],
    "functions": [
        {
            "ncname": "GetOffersFunction",
            "documentation": {
                "german": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>",
                "english": "<?xml version='1.0' encoding='UTF-8' ?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body><p/></body></html>"
            },
            "inputElementName": {
                "namespaceuri": "http://www.myshuttle.io",
                "ncname": "GetOffersRequest"
            },
            "outputElementName": {
                "namespaceuri": "http://www.myshuttle.io",
                "ncname": "GetOffersResponse"
            },
            "assertions": [
                {
                    "test": "every $offer in GetOffersResponse/GetOffersSuccess/Offer satisfies $offer/From/WalkWayInMeters le GetOffersRequest/From/FlexibilityInMeters"
                },
